version: '3'
services:
  otel-collector:
    image: otel/opentelemetry-collector
    volumes:
      - ./otel_collector_config.yaml:/otel_collector_config.yaml
    ports:
      - "4317:4317"  # OTLP gRPC port
      - "4318:4318"  # OTLP HTTP port (make sure to add this for metrics and traces)
    command: ["--config=/otel_collector_config.yaml"]

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"  # Zipkin web interface
