receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  new_relic:
    api_key: "eu01xx420746d2c419da3f475ddb0c5cFFFFNRAL"  # Use your New Relic API key
    region: "EU"  # Use "EU" for your New Relic account region
    service: "textile-plm-digitalisation"  # Change this to match the service name in your instrumentation.ts

  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"  # Zipkin exporter

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [new_relic, zipkin]  # Send traces to both New Relic and Zipkin

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [new_relic]  # Send metrics only to New Relic

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [new_relic]  # Send logs only to New Relic

    errors:
      receivers: [otlp]
      processors: [batch]
      exporters: [new_relic]  # Send errors only to New Relic

    custom_events:
      receivers: [otlp]
      processors: [batch]
      exporters: [new_relic]  # Send custom events only to New Relic
